# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-09 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
        ('crm', '0004_auto_20181209_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='name',
            field=models.CharField(default='x', max_length=32, verbose_name='用户名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='password',
            field=models.CharField(default='y', max_length=32, verbose_name='密码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='roles',
            field=models.ManyToManyField(to='rbac.Role', verbose_name='用户拥有的角色'),
        ),
    ]
