# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-09 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=64, verbose_name='含正则的URL地址')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('name', models.CharField(max_length=32, verbose_name='URL别名')),
                ('is_menu', models.BooleanField(default=False, verbose_name='是否是菜单')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='角色名')),
                ('permissions', models.ManyToManyField(to='rbac.Permission', verbose_name='角色拥有的权限')),
            ],
        ),
    ]
